name: WinGet
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest          
    steps:
      - name: Install WinGet
        shell: powershell
        run: |
          mkdir C:/creation
          cd C:/creation
          curl https://github.com/microsoft/winget-create/releases/download/v1.2.5.0/wingetcreate.exe -o wingetcreate.exe
          
      - run: |
          cd C:/creation
          ls
          .\wingetcreate.exe 
      - name: Install wingetcreate
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          cd C:/creation
          ls
          .\wingetcreate token -s -t ${{ env.TOKEN }}
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
