name: WinGet
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install WinGet
        shell: powershell
        run: |
          mkdir C:/creation
          cd C:/creation
          curl https://github.com/microsoft/winget-create/releases/download/v1.2.5.0/wingetcreate.exe -o wingetcreate.exe

      - run: |
          cd C:/creation
          ls
          .\wingetcreate.exe 
      - name: Install wingetcreate
        env: 
          # Add a 'GITHUB_TOKEN' secret to your repository's secrets to access it here
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Set 'GITHUB_TOKEN' as an environment variable and pass it to the wingetcreate command
        run: | 
          cd C:/creation
          ls
          # Use the '$GITHUB_TOKEN' environment variable instead of '${{ env.TOKEN }}'
          .\wingetcreate token -s -t $GITHUB_TOKEN
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
