name: WinGet
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install WinGet
        shell: powershell
        run: |
          curl https://github.com/microsoft/winget-create/releases/download/v1.2.5.0/wingetcreate.exe
          
      - run: |
          .\wingetcreate.exe --info
      - name: Install wingetcreate
        run: | 
          .\wingetcreate token -s -t ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
