name: WinGet
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
          winget install wingetcreate
          wingetcreate token -s -t ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3.2.1
